name: Build

on: push

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '17'
                  cache: 'maven'
            - run: ./mvnw -version
            - run: ./mvnw -U verify -DfailIfNoTests
            - uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: it-logs
                  path: target/it/**/build.log
            - uses: codecov/codecov-action@v3
