name: Deploy to OSSRH

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '17'
                  server-id: ossrh
                  server-username: MAVEN_USERNAME
                  server-password: MAVEN_PASSWORD
                  gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
                  gpg-passphrase: MAVEN_GPG_PASSPHRASE
            - name: 🚀 Deploy artifact
              run: |
                  mvn help:effective-settings
                  mvn -B --no-transfer-progress -DskipTests -DperformRelease=true deploy
              env:
                  MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
                  MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
